version: '3.8'

services:
    ios-icons:
        container_name: ios-icons
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: ios-icons:0.1
        ports:
            - 81:5000 # Dev
            - 82:5001 # Preview
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./frontend:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev