version: '3.8'

services:
    ios-icons:
        container_name: ios-icons
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: ios-icons:1.0
        ports:
            - 80:5000 # Dev
            - 81:5001 # Preview
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./frontend:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        # command: tail -F anything
        command: npm run dev